# TS Frontend parameters
minWorkers: 1
maxWorkers: 1
batchSize: 1
maxBatchDelay: 100
responseTimeout: 120
deviceType: gpu # cpu, gpu, neuron
parallelLevel: 4 # rpc world size
parallelType: pp # pp: pipeline parallel; pptp: tensor+pipeline parallel




