# TorchServe frontend parameters
minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 120
parallelType: "tp"
deviceType: "gpu"

torchrun:
    nproc-per-node: 4

# TorchServe Backend parameters
deepspeed:
    config: ds-config.json

handler:
    max_length: 80
