# TorchServe frontend parameters
minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 1200
deviceType: "gpu"

handler:
    model_name: "meta-llama/Llama-2-70b-chat-hf"
    max_length: 50
    max_new_tokens: 50
    manual_seed: 40
