name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
    - name: Run Regression GPU Test
      if: contains(github.event.comment.body, '/regression-gpu')   # check the comment if it contains the keywords
      uses: pytorch/serve/.github/workflows/regression_tests_gpu.yml@feature/run_regression_issue_comment
      with:
        event_name: ${{ github.event_name }}
        run_id: ${{ github.run_id }}
