name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-build-and-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TorchServe
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Test model running in k8s cluster with sample image data
        run: ./kubernetes/scripts/test_k8s_model_prediction.sh
