name: k8s CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-model-prediction-on-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TorchServe
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev

      - name: Install TorchServe
        run: |
          python ts_scripts/install_from_src.py
      - name: Build Docker Image
        working-directory: docker
        run: |
          ./build_image.sh -bt dev -t pytorch/torchserve:latest-cpu"
      - name: Test model running in k8s cluster with sample image data
        run: ./kubernetes/scripts/test_k8s_model_prediction.sh
