## Call setup.py with pytorch credentials
## Ignore tests
# Where is this pushed and under what name?

name: Push Nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'

jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchSeve
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -eux
          pip install -e .
          pip install twine
#       - name: Run tests
#         run: python -m unittest discover --verbose --start-directory . --pattern "*_test.py"
      - name: Push nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: ts_scripts/push_nightly.sh
        