name: Make an official Release

on: workflow_dispatch

jobs:
  official-release:
    # creates workflows for the 3 OS: ubuntu, macOS & windows
    runs-on: [self-hosted, ci-gpu]

    # The official-release environment requires 2 manual approvals
    environment:
      name: official-release
    strategy:
      fail-fast: true
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
          pip install -e .
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login --username pytorchbot --password "$DOCKER_PASSWORD"
      - name: Build & Upload pytorch/torchserve-kfs Docker images
        run: |
          cd kubernetes/kserve
          python build_upload_release.py
          cd ..
