name: Make an official Release

on: workflow_dispatch

jobs:
  official-release:
    # creates workflows for the 3 OS: ubuntu, macOS & windows
    runs-on: ${{ matrix.os }}

    # The official-release environment requires 2 manual approvals
    environment:
      name: official-release
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macOS-latest, windows-latest]
    steps:
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - name: Setup Anaconda
        run: |
          conda --version
          conda install -y conda-build anaconda-client
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
          pip install -e .
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build PyPI & conda binaries
        run: python binaries/build.py
      - name: Push conda binaries
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_PASSWORD }}
        run: python binaries/upload.py --upload-conda-packages
