name: Raise Github Issue on Failure

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
      run_id:
        required: true
        type: string
      test_name:
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Open github issue on failure
        if: ${{ failure() && inputs.event_name == 'push' }}
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.test_name }} failed
          body: Commit ${{ github.sha }} daily scheduled [${{ inputs.test_name }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
          assignees: ''
