name: Run Regression Tests on GPU

on:
  push:
  #  branches:
  #    - master
  #pull_request:
  #  branches:
  #    - master

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-regression:
    strategy:
      fail-fast: false
      matrix:
        hardware: [ubuntu-20.04, [self-hosted, regression-test-gpu]]
    runs-on:
      - ${{ matrix.hardware }}
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          cd $RUNNER_WORKSPACE
          pwd
          cd ..
          pwd
          sudo rm -rf _tool
          docker system prune -f

      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Build CPU Docker Image
        #if: ${{ matrix.hardware == 'ubuntu-20.04' }}
        if: contains(matrix.hardware, 'ubuntu')
        run: |
          cd docker
          ./build_image.sh -bt ci -t pytorch/torchserve:ci
      - name: Build GPU Docker Image
        if: contains(matrix.hardware, 'gpu')
        run: |
          cd docker
          ./build_image.sh -g -cv cu117 -bt ci -t pytorch/torchserve:ci
      - name: Torchserve GPU Regression Tests
        if: contains(matrix.hardware, 'gpu')
        run: |
          docker run --gpus all -v $GITHUB_WORKSPACE:/home/serve pytorch/torchserve:ci
      - name: Torchserve CPU Regression Tests
        if: contains(matrix.hardware, 'ubuntu')
        run: |
          docker run -v $GITHUB_WORKSPACE:/home/serve pytorch/torchserve:ci
      - name: Cleanup
        run: |
          docker system prune -f && docker rmi pytorch/torchserve:ci
          sudo rm -rf serve
