name: Temp workflow to download Llama 7B weights

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  nightly:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, gpu]
    timeout-minutes: 1320
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          cd $RUNNER_WORKSPACE
          pwd
          cd ..
          pwd
          rm -rf _tool
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download weights
        env:
          HUGGING_FACE_HUB_TOKEN: ${{secrets.HUGGING_FACE_HUB_TOKEN}}
        run: |
          sudo apt-get update -y
          cd /home/ubuntu
          git clone https://github.com/pytorch-labs/gpt-fast/
          pip install sentencepiece huggingface_hub
          pip install chardet
          pip uninstall torchtext torchdata torch torchvision torchaudio -y
          pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121 --ignore-installed
          export MODEL_REPO=meta-llama/Llama-2-7b-chat-hf
          cd gpt-fast
          huggingface-cli login --token $HUGGING_FACE_HUB_TOKEN
          ./scripts/prepare.sh $MODEL_REPO
          python quantize.py --checkpoint_path checkpoints/$MODEL_REPO/model.pth --mode int4